name: simpler_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.12.14=hbcca054_0
  - comm=0.2.2=pyhd8ed1ab_1
  - debugpy=1.8.11=py310hf71b8c6_0
  - decorator=5.1.1=pyhd8ed1ab_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - importlib-metadata=8.5.0=pyha770c72_1
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.31.0=pyh707e725_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - krb5=1.21.3=h143b758_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgomp=14.2.0=h77fa898_1
  - libsodium=1.0.20=h4ab18f5_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.4.0=hb9d3cd8_0
  - packaging=24.2=pyhd8ed1ab_2
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=24.2=py310h06a4308_0
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - prompt-toolkit=3.0.48=pyha770c72_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.18.0=pyhd8ed1ab_1
  - python=3.10.15=he870216_1
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.10=2_cp310
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py310h06a4308_0
  - six=1.17.0=pyhd8ed1ab_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.14=h39e8969_0
  - tornado=6.4.2=py310ha75aee5_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.44.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - accelerate==1.2.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyio==4.7.0
      - async-timeout==5.0.1
      - attrs==24.3.0
      - automated-interpretability==0.0.6
      - babe==0.0.7
      - beartype==0.14.1
      - beautifulsoup4==4.12.3
      - better-abc==0.0.3
      - blobfile==2.1.1
      - boostedblob==0.15.5
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - click==8.1.8
      - cloudpickle==3.1.0
      - config2py==0.1.36
      - contourpy==1.3.1
      - cycler==0.12.1
      - datasets==2.21.0
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - dol==0.2.95
      - einops==0.8.0
      - fancy-einsum==0.0.3
      - farama-notifications==0.0.4
      - filelock==3.16.1
      - fonttools==4.55.3
      - frozenlist==1.5.0
      - fsspec==2024.6.1
      - gdown==5.2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gprof2dot==2024.6.6
      - graze==0.1.27
      - gymnasium==0.29.1
      - h11==0.14.0
      - h5py==3.12.1
      - httpcore==1.0.7
      - httpx==0.27.2
      - huggingface-hub==0.27.0
      - i2==0.1.45
      - idna==3.10
      - imageio==2.36.0
      - imageio-ffmpeg==0.5.1
      - importlib-resources==6.4.5
      - iniconfig==2.0.0
      - ipykernel==6.29.5
      - jaxtyping==0.2.36
      - jinja2==3.1.5
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - lxml==4.9.4
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - networkx==3.4.2
      - nltk==3.9.1
      - numpy==1.24.4
      - nnsight==0.4.1
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - openai==1.61.1
      - opencv-python==4.10.0.84
      - orjson==3.10.13
      - pandas==2.2.3
      - patsy==1.0.1
      - pillow==11.0.0
      - plotly==5.24.1
      - plotly-express==0.4.1
      - pluggy==1.5.0
      - propcache==0.2.1
      - protobuf==5.29.2
      - psutil==6.1.0
      - py2store==0.1.20
      - pyarrow==18.1.0
      - pycryptodomex==3.21.0
      - pydantic==2.10.4
      - pydantic-core==2.27.2
      - pyparsing==3.2.1
      - pysocks==1.7.1
      - pytest==8.3.4
      - pytest-profiling==1.8.1
      - python-dotenv==1.0.1
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==26.0.0
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - rtree==1.3.0
      - ruckig==0.14.0
      - sae-lens==5.3.0
      - safetensors==0.4.5
      - sapien==2.2.2
      - scikit-learn==1.6.0
      - scipy==1.14.1
      - sentencepiece==0.2.0
      - sentry-sdk==2.19.2
      - setproctitle==1.3.4
      - shellingham==1.5.4
      - simple-parsing==0.1.6
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.6
      - statsmodels==0.14.4
      - sympy==1.13.1
      - tabulate==0.9.0
      - tenacity==9.0.0
      - threadpoolctl==3.5.0
      - tiktoken==0.6.0
      - tokenizers==0.21.0
      - tomli==2.2.1
      - torch==2.5.1
      - tqdm==4.67.0
      - transformer-lens==2.11.0
      - transformers==4.47.1
      - transforms3d==0.4.2
      - trimesh==4.5.2
      - triton==3.1.0
      - typeguard==4.4.1
      - typer==0.12.5
      - tzdata==2024.2
      - urllib3==2.2.3
      - uvloop==0.21.0
      - wandb==0.19.1
      - xxhash==3.5.0
      - yarl==1.18.3
      - zstandard==0.22.0
prefix: /homes/55/constantin/miniconda3/envs/simpler_env
